version: '3.1'
services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: root
#            MONGO_INITDB_ROOT_PASSWORD: example123

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
#        environment:
#            ME_CONFIG_MONGODB_ADMINUSERNAME: root
#            ME_CONFIG_MONGODB_ADMINPASSWORD: example123
        depends_on:
            -   mongo

    app-name:
        image: java-name
        ports:
        -   8082:8080
        environment:
            DB_HOST: mongo
            DB_PORT: 27010
            DB_NAME: db-prod
            SPRING_PROFILES_ACTIVE: prod
        depends_on:
            -   mongo